# Agricultural Raw Material prices (1990-2020)

This is a dataset is on *Agricultural Raw materials prices over a span of 30 years (1990-2020)*. You can find this dataset on [Kaggle](https://www.kaggle.com/kianwee/agricultural-raw-material-prices-19902020). Mainly this dataset contains information about the **prices** and the **percent change in the prices from the previous month**. The prices are present for every month. So we are going to analyse this dataset to get the *distribution of the prices* and *the distribution of the change in prices*. We also want to gain some insights regarding *the months when the prices of most of the materials falls*. We will also like to see the trends in the prices.

*This dataset contains information about 12 Agricultural Raw Materials.*

- **Coarse wool**
- **Copra**
- **Cotton**
- **Fine wool**
- **Hardlog**
- **Hard sawnwood**
- **Hide**
- **Plywood**
- **Rubber**
- **Softlog**
- **Soft sawnwood**
- **Wood pulp**

For each material we have two columns: **Prices** and **%change**. Along with all these columns we have another one column named **Date** which contains month and year of which the price is. This is a course project for the online course at [Jovian.ml](https://jovian.ml/) named [Data Analysis with Python: Zero to Pandas](https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas).

### How to run the code

This is an executable [*Jupyter notebook*](https://jupyter.org) hosted on [Jovian.ml](https://www.jovian.ml), a platform for sharing data science projects. You can run and experiment with the code in a couple of ways: *using free online resources* (recommended) or *on your own computer*.

#### Option 1: Running using free online resources (1-click, recommended)

The easiest way to start executing this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on [mybinder.org](https://mybinder.org), a free online service for running Jupyter notebooks. You can also select "Run on Colab" or "Run on Kaggle".


#### Option 2: Running on your computer locally

1. Install Conda by [following these instructions](https://conda.io/projects/conda/en/latest/user-guide/install/index.html). Add Conda binaries to your system `PATH`, so you can use the `conda` command on your terminal.

2. Create a Conda environment and install the required libraries by running these commands on the terminal:

```
conda create -n zerotopandas -y python=3.8 
conda activate zerotopandas
pip install jovian jupyter numpy pandas matplotlib seaborn opendatasets --upgrade
```

3. Press the "Clone" button above to copy the command for downloading the notebook, and run it on the terminal. This will create a new directory and download the notebook. The command will look something like this:

```
jovian clone notebook-owner/notebook-id
```



4. Enter the newly created directory using `cd directory-name` and start the Jupyter notebook.

```
jupyter notebook
```

You can now access Jupyter's web interface by clicking the link that shows up on the terminal or by visiting http://localhost:8888 on your browser. Click on the notebook file (it has a `.ipynb` extension) to open it.

## Downloading the dataset

As the dataset is present in the  [`opendatasets` Python library](https://github.com/JovianML/opendatasets#opendatasets) so we are going to download it directly from there using the `opendatasets.download()` command

In [1]:
!pip install jovian opendatasets --upgrade --quiet

Let's begin by downloading the data, and listing the files within the dataset.

In [2]:
# Dataset url
dataset_url = 'https://www.kaggle.com/kianwee/agricultural-raw-material-prices-19902020'

In [3]:
import opendatasets as od
od.download(dataset_url)

Kaggle dataset ID:  kianwee/agricultural-raw-material-prices-19902020

0it [00:00, ?it/s]

Downloading https://www.kaggle.com/kianwee/agricultural-raw-material-prices-19902020/download?resource=download&downloadHash=e3d3e5f84c73a2fd1c7b835dbc4b37e5c64a58448ebc43a13eaee28de0d15828 to .\agricultural-raw-material-prices-19902020.zip

24576it [00:02, 12109.03it/s]

Extracting archive .\agricultural-raw-material-prices-19902020.zip to .\agricultural-raw-material-prices-19902020

In [4]:
# Dataset directory path
data_dir = r'.\agricultural-raw-material-prices-19902020'

In [5]:
import os
os.listdir(data_dir)

['agricultural_raw_material.csv']

Let us save and upload our work to Jovian before continuing.

In [6]:
# Name of the project by which we are going to save this at Jovian
project_name = "agricultural-raw-material-prices"

In [7]:
!pip install jovian --upgrade -q

In [8]:
import jovian
jovian.commit(project=project_name)

[jovian] Attempting to save notebook..
[jovian] Creating a new project "adhikarisayanta/agricultural-raw-material-prices"
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/adhikarisayanta/agricultural-raw-material-prices

'https://jovian.ml/adhikarisayanta/agricultural-raw-material-prices'

## Data Preparation and Cleaning

In this step we are going to prepare our data for the further analysis. We will look at the overall view of the dataset, look for null values, outliers (if any). We will try to remove those null values and outliers to make the upcoming analysis easier for us.<br>
We are going to import the dataset into a `pandas.DataFrame` and do the cleaning.

Let's first import the required libraries for this session

In [9]:
import numpy as np
import pandas as pd

Now let's read the dataset into a DataFrame named `prices_df`

In [11]:
prices_df = pd.read_csv(r'.\agricultural-raw-material-prices-19902020\agricultural_raw_material.csv')
prices_df.head(10)

,Month,Coarse wool Price,Coarse wool price % Change,Copra Price,Copra price % Change,Cotton Price,Cotton price % Change,Fine wool Price,Fine wool price % Change,Hard log Price,...,Plywood Price,Plywood price % Change,Rubber Price,Rubber price % Change,Softlog Price,Softlog price % Change,Soft sawnwood Price,Soft sawnwood price % Change,Wood pulp Price,Wood pulp price % Change
0,Apr-90,482.34,-,236,-,1.83,-,"1,071.63",-,161.20,...,312.36,-,0.84,-,120.66,-,218.76,-,829.29,-
1,May-90,447.26,-7.27%,234,-0.85%,1.89,3.28%,"1,057.18",-1.35%,172.86,...,350.12,12.09%,0.85,1.19%,124.28,3.00%,213.00,-2.63%,842.51,1.59%
2,Jun-90,440.99,-1.40%,216,-7.69%,1.99,5.29%,898.24,-15.03%,181.67,...,373.94,6.80%,0.85,0.00%,129.45,4.16%,200.00,-6.10%,831.35,-1.32%
3,Jul-90,418.44,-5.11%,205,-5.09%,2.01,1.01%,895.83,-0.27%,187.96,...,378.48,1.21%,0.86,1.18%,124.23,-4.03%,210.05,5.03%,798.83,-3.91%
4,Aug-90,418.44,0.00%,198,-3.41%,1.79,-10.95%,951.22,6.18%,186.13,...,364.60,-3.67%,0.88,2.33%,129.70,4.40%,208.30,-0.83%,818.74,2.49%
5,Sep-90,412.18,-1.50%,196,-1.01%,1.79,0.00%,936.77,-1.52%,185.33,...,384.92,5.57%,0.90,2.27%,129.78,0.06%,199.59,-4.18%,811.62,-0.87%
6,Oct-90,394.64,-4.26%,198,1.02%,1.79,0.00%,901.85,-3.73%,189.76,...,409.31,6.34%,0.90,0.00%,121.31,-6.53%,206.98,3.70%,807.46,-0.51%
7,Nov-90,334.5,-15.24%,236,19.19%,1.82,1.68%,888.61,-1.47%,179.02,...,375.74,-8.20%,0.90,0.00%,130.50,7.58%,206.64,-0.16%,773.37,-4.22%
8,Dec-90,328.24,-1.87%,237,0.42%,1.85,1.65%,870.55,-2.03%,171.13,...,363.16,-3.35%,0.88,-2.22%,119.35,-8.54%,198.22,-4.07%,741.29,-4.15%
9,Jan-91,319.47,-2.67%,233,-1.69%,1.85,0.00%,887.41,1.94%,169.19,...,362.26,-0.25%,0.87,-1.14%,126.14,5.69%,186.94,-5.69%,721.85,-2.62%

In [13]:
prices_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 361 entries, 0 to 360
Data columns (total 25 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Month                         361 non-null    object
 1   Coarse wool Price             327 non-null    object
 2   Coarse wool price % Change    327 non-null    object
 3   Copra Price                   339 non-null    object
 4   Copra price % Change          339 non-null    object
 5   Cotton Price                  361 non-null    float64
 6   Cotton price % Change         361 non-null    object
 7   Fine wool Price               327 non-null    object
 8   Fine wool price % Change      327 non-null    object
 9   Hard log Price                361 non-null    float64
 10  Hard log price % Change       361 non-null    object
 11  Hard sawnwood Price           327 non-null    float64
 12  Hard sawnwood price % Change  327 non-null    object
 13  Hide Price                    327 non-null    float64
 14  Hide price % change           327 non-null    object
 15  Plywood Price                 361 non-null    float64
 16  Plywood price % Change        361 non-null    object
 17  Rubber Price                  361 non-null    float64
 18  Rubber price % Change         361 non-null    object
 19  Softlog Price                 327 non-null    float64
 20  Softlog price % Change        327 non-null    object
 21  Soft sawnwood Price           327 non-null    float64
 22  Soft sawnwood price % Change  327 non-null    object
 23  Wood pulp Price               360 non-null    float64
 24  Wood pulp price % Change      360 non-null    object
dtypes: float64(9), object(16)
memory usage: 70.6+ KB

In [14]:
prices_df.describe()

,Cotton Price,Hard log Price,Hard sawnwood Price,Hide Price,Plywood Price,Rubber Price,Softlog Price,Soft sawnwood Price,Wood pulp Price
count,361.000000,361.000000,327.000000,327.000000,361.000000,361.000000,327.000000,327.000000,360.000000
mean,1.640000,251.034072,707.950367,78.566667,508.216122,1.656427,164.527462,291.061713,696.670889
std,0.513319,65.628406,144.563241,13.690623,89.274718,1.017086,25.596308,34.113959,161.156936
min,0.820000,133.280000,413.370000,28.590000,312.360000,0.490000,119.350000,183.610000,384.000000
25%,1.290000,197.960000,573.470000,69.495000,442.540000,0.860000,145.970000,277.590000,549.777500
50%,1.600000,253.010000,728.710000,77.250000,505.040000,1.440000,160.370000,294.960000,693.580000
75%,1.850000,282.970000,831.635000,86.000000,570.790000,2.060000,180.210000,310.865000,875.000000
max,5.060000,520.810000,973.600000,114.630000,751.810000,6.260000,259.970000,372.600000,966.490000

After studying the dataset and the info() of it we came to know that last values of few columns are empty and if we remove them for the whole dataset then we can loose alot of information. So we are not going to remove them rather we are going to deal with them when we do the EDA (material-wise). <br>

Another point is that all the **%Change** columns are strings not numbers so, we are going to convert them into numbers between 0 to 100.<br>

Another thing is that the **Date** column contains both *month* and *year* together (MMM-YY). So we would like to separate them as it would help us to gain more insights.

Let's define a function to change the **%Change** column to the desired format.

In [30]:
# function to change the %Change column from string to float
def percent_to_float(percent):
    import math
    if percent == '-':
        return np.nan
    elif type(percent) == float:
        return np.nan
    else:
        percent = percent.rstrip('%')
        num = float(percent)
        return percent
    return np.nan

In [31]:
prices_df.columns

Index(['Month', 'Coarse wool Price', 'Coarse wool price % Change',
       'Copra Price', 'Copra price % Change', 'Cotton Price',
       'Cotton price % Change', 'Fine wool Price', 'Fine wool price % Change',
       'Hard log Price', 'Hard log price % Change', 'Hard sawnwood Price',
       'Hard sawnwood price % Change', 'Hide Price', 'Hide price % change',
       'Plywood Price', 'Plywood price % Change', 'Rubber Price',
       'Rubber price % Change', 'Softlog Price', 'Softlog price % Change',
       'Soft sawnwood Price', 'Soft sawnwood price % Change',
       'Wood pulp Price', 'Wood pulp price % Change'],
      dtype='object')

In [32]:
# Getting the column names on which we need to apply this function percent_to_float
columns = ['Coarse wool price % Change', 'Copra price % Change',
       'Cotton price % Change', 'Fine wool price % Change',
       'Hard log price % Change', 'Hard sawnwood price % Change',
       'Hide price % change', 'Plywood price % Change', 
       'Rubber price % Change',  'Softlog price % Change',
       'Soft sawnwood price % Change',  'Wood pulp price % Change']

In [33]:
for column in columns:
    prices_df[column] = prices_df[column].apply(percent_to_float)
prices_df.head()

,Month,Coarse wool Price,Coarse wool price % Change,Copra Price,Copra price % Change,Cotton Price,Cotton price % Change,Fine wool Price,Fine wool price % Change,Hard log Price,...,Plywood Price,Plywood price % Change,Rubber Price,Rubber price % Change,Softlog Price,Softlog price % Change,Soft sawnwood Price,Soft sawnwood price % Change,Wood pulp Price,Wood pulp price % Change
0,Apr-90,482.34,NaN,236,NaN,1.83,NaN,"1,071.63",NaN,161.20,...,312.36,NaN,0.84,NaN,120.66,NaN,218.76,NaN,829.29,NaN
1,May-90,447.26,-7.27,234,-0.85,1.89,3.28,"1,057.18",-1.35,172.86,...,350.12,12.09,0.85,1.19,124.28,3.00,213.00,-2.63,842.51,1.59
2,Jun-90,440.99,-1.40,216,-7.69,1.99,5.29,898.24,-15.03,181.67,...,373.94,6.80,0.85,0.00,129.45,4.16,200.00,-6.10,831.35,-1.32
3,Jul-90,418.44,-5.11,205,-5.09,2.01,1.01,895.83,-0.27,187.96,...,378.48,1.21,0.86,1.18,124.23,-4.03,210.05,5.03,798.83,-3.91
4,Aug-90,418.44,0.00,198,-3.41,1.79,-10.95,951.22,6.18,186.13,...,364.60,-3.67,0.88,2.33,129.70,4.40,208.30,-0.83,818.74,2.49

Now all the **%Change** columns are converted into floats. Now let's move on to the next problem.

Let's make two new columns from the **Date** column: one containing **month** and another containing **year**

In [34]:
# Function that takes input the date and returns the month or year as per requirement
def mon_yr(date, what):
    l = date.split('-')
    if what == 'month':
        return l[0]
    elif what == 'year':
        return l[1]

In [35]:
prices_df['month_name'] = prices_df['Month'].apply(mon_yr, args=('month',))
prices_df['year'] = prices_df['Month'].apply(mon_yr, args=('year',))
prices_df.head(8)

,Month,Coarse wool Price,Coarse wool price % Change,Copra Price,Copra price % Change,Cotton Price,Cotton price % Change,Fine wool Price,Fine wool price % Change,Hard log Price,...,Rubber Price,Rubber price % Change,Softlog Price,Softlog price % Change,Soft sawnwood Price,Soft sawnwood price % Change,Wood pulp Price,Wood pulp price % Change,month_name,year
0,Apr-90,482.34,NaN,236,NaN,1.83,NaN,"1,071.63",NaN,161.20,...,0.84,NaN,120.66,NaN,218.76,NaN,829.29,NaN,Apr,90
1,May-90,447.26,-7.27,234,-0.85,1.89,3.28,"1,057.18",-1.35,172.86,...,0.85,1.19,124.28,3.00,213.00,-2.63,842.51,1.59,May,90
2,Jun-90,440.99,-1.40,216,-7.69,1.99,5.29,898.24,-15.03,181.67,...,0.85,0.00,129.45,4.16,200.00,-6.10,831.35,-1.32,Jun,90
3,Jul-90,418.44,-5.11,205,-5.09,2.01,1.01,895.83,-0.27,187.96,...,0.86,1.18,124.23,-4.03,210.05,5.03,798.83,-3.91,Jul,90
4,Aug-90,418.44,0.00,198,-3.41,1.79,-10.95,951.22,6.18,186.13,...,0.88,2.33,129.70,4.40,208.30,-0.83,818.74,2.49,Aug,90
5,Sep-90,412.18,-1.50,196,-1.01,1.79,0.00,936.77,-1.52,185.33,...,0.90,2.27,129.78,0.06,199.59,-4.18,811.62,-0.87,Sep,90
6,Oct-90,394.64,-4.26,198,1.02,1.79,0.00,901.85,-3.73,189.76,...,0.90,0.00,121.31,-6.53,206.98,3.70,807.46,-0.51,Oct,90
7,Nov-90,334.5,-15.24,236,19.19,1.82,1.68,888.61,-1.47,179.02,...,0.90,0.00,130.50,7.58,206.64,-0.16,773.37,-4.22,Nov,90

Now we have also added the new required columns. So, more or less the data preparation and cleaning part is over. Lets move on to the next part.

Before that let's save and upload our work to Jovian

In [38]:
jovian.commit(project=project_name)

[jovian] Attempting to save notebook..
[jovian] Updating notebook "adhikarisayanta/agricultural-raw-material-prices" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/adhikarisayanta/agricultural-raw-material-prices

'https://jovian.ml/adhikarisayanta/agricultural-raw-material-prices'